import { homePageMockData } from '@root/__mock-props__/component/view/home';
import { HomePage } from '@src/components/view';
import { IHomePage } from '@src/types/view';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
const Home: React.FC<{ homePageData: IHomePage }> = ({ homePageData }) => {
  return (
    <div>
      <Head>
        <title>Agency Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomePage {...homePageData} />
      </main>
    </div>
  );
};

export async function getStaticProps() {
  return {
    props: {
      homePageData: homePageMockData,
    }, // will be passed to the page component as props
  };
}

export default Home;
